---
- name: Create Output DIR
  file:
    path: "./config_files/base_conf_rendered_config"
    state: directory
  run_once: true

- name: Templating base_conf Config
  template:
    src: base_conf.j2
    dest: "./config_files/base_conf_rendered_config/{{ inventory_hostname }}.conf"

#- name: Pushing VXLAN Config
#  juniper_junos_config:
#    provider: "{{ junos_provider }}"
#    src: "./config_files/interfaces_rendered_config/{{ inventory_hostname }}.conf"
