---
- name: Create Output DIR
  file:
    path: "./config_files/interfaces_rendered_config"
    state: directory
  run_once: true

- name: Templating VXLAN Config
  template:
    src: interfaces.j2
    dest: "./config_files/interfaces_rendered_config/{{ inventory_hostname }}.conf"

- name: Pushing Interface Config
  junos_config:
    src: "./config_files/interfaces_rendered_config/{{ inventory_hostname }}.conf"
