---
name: "Leaf-1"
role: "Leaf"

#Interface Section
interfaces:
  - interface: xe-0/0/0
    ipv4: "10.0.0.1"
    ipv4_mask: 31
    description: '"Link to Spine-1"'
    type: "routed"
  - interface: lo0
    ipv4: "10.255.254.10"
    ipv4_mask: 32
    description: '"Management IP"'
    type: "loopback"

#BGP Sections
asn: 64520
router_id: 10.255.254.10
bgp_networks:
  - "100.127.10.1/32"
bgp_neighbor:
  - remote_address: "10.0.0.0"
    local_address: "10.0.0.1"
    remote_asn: "64512"
    description: '"eBGP_Underlay to Spine-1"'
    group: "Underlay"
    bfd: "true"
  - remote_address: "10.255.254.0"
    local_address: "10.255.254.10"
    remote_asn: "64512"
    description: '"eBGP_Underlay to Spine-1"'
    group: "Overlay"
    bfd: "true"

#VXLAN Section
vxlan:
  - vni: "1010"
    rd: "1:1010"
    community: "com1010"
    vrf: "Cust-A"
    vlan_id: 10
    vlan_name: "BD1010"
    vlan_description: "VXLAN Test VLAN"
    irb_id: 10
    irb_description: "VXLAN Test VLAN"
    ipv4_gw: "10.10.10.1"
    ipv4_mask: 24
    intf:
      xe-0/0/0:
        type: "access"
