---
name: "Leaf-2"
role: "Leaf"

#Interface Section
l3_interfaces:
  - interface: xe-0/0/0
    unit: 0
    ipv4: "10.0.2.3"
    ipv4_mask: 31
    description: "Link to Spine-2"
    type: "routed"
  - interface: xe-0/0/0
    unit: 0
    ipv4: "10.0.1.3"
    ipv4_mask: 31
    description: "Link to Spine-1"
    type: "routed"
  - interface: lo0
    unit: 0
    ipv4: "10.255.254.12"
    ipv4_mask: 32
    description: "Router ID"
    type: "loopback"
  - interface: lo0
    unit: 1
    ipv4: "10.255.254.12"
    ipv4_mask: 32
    description: "Cust-A RI Loopback"
    routing_instance: "Cust-A"
  - interface: em0
    unit: 0
    ipv4: "10.255.255.12"
    ipv4_mask: 24
    description: "Management IP"
    type: "em"
  - interface: em1
    unit: 0
    ipv4: "169.254.0.2"
    ipv4_mask: 24
    description: "Link to vPFE"
    type: "em"
  - interface: irb
    unit: 10
    ipv4: "10.10.100.1"
    ipv4_mask: 24
    description: "BD1010 Gateway"
    type: "irb"

l2_interfaces:
  - interface: xe-0/0/9
    vlan:
      - "BD1010"
    description: "Link to Ubuntu-2"
    mode: "access"

routing_instances:
  - name: "Cust-A"
    instance_type: "virtual-router"
    interfaces:
      - "irb.10"
      - "lo0.1"

#BGP Sections
asn: 64521
router_id: 10.255.254.12
bgp_networks:
  - "100.127.10.1/32"
bgp_underlay:
  - remote_address: "10.0.1.2"
    local_address: "10.0.1.3"
    remote_asn: "64512"
    description: "eBGP_Underlay to Spine-1"
    bfd: "true"
  - remote_address: "10.0.2.2"
    local_address: "10.0.2.3"
    remote_asn: "64513"
    description: "eBGP_Underlay to Spine-2"
    bfd: "true"
bgp_overlay:
  - remote_address: "10.255.254.1"
    remote_asn: "64512"
    description: "eBGP_Overlay to Spine-1"
    bfd: "true"
  - remote_address: "10.255.254.2"
    remote_asn: "64513"
    description: "eBGP_Overlay to Spine-2"
    bfd: "true"

#VXLAN Section
vxlan:
  - vni: "1010"
    rd: "1:1010"
    community: "com1010"
    vlan_id: 10
    vlan_name: "BD1010"
    vlan_description: "VXLAN Test VLAN"
