---
- name: Create Output DIR
  file:
    path: "./config_files/bgp_rendered_config"
    state: directory
  run_once: true

- name: Templating BGP Config
  template:
    src: bgp.j2
    dest: "./config_files/bgp_rendered_config/{{ inventory_hostname }}.conf"

- name: Pushing BGP Config
  junos_config:
    src: "./config_files/bgp_rendered_config/{{ inventory_hostname }}.conf"
    update: replace
